# Generated by Django 4.0.3 on 2022-05-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default=None, null=True)),
                ('due_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('owner', models.CharField(max_length=100)),
                ('mark', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('task',),
            },
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='todo',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.todolist'),
        ),
    ]
